FROM node:20-slim AS base

WORKDIR /app

# Install dependencies
COPY package.json package-lock.json ./
RUN npm ci

# Copy source
COPY . .

# NEXT_PUBLIC_ vars baked in at build time (passed from Railway)
ARG NEXT_PUBLIC_SUPABASE_URL
ARG NEXT_PUBLIC_SUPABASE_ANON_KEY
ARG NEXT_PUBLIC_APP_URL
ARG NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY
ENV NEXT_PUBLIC_SUPABASE_URL=$NEXT_PUBLIC_SUPABASE_URL
ENV NEXT_PUBLIC_SUPABASE_ANON_KEY=$NEXT_PUBLIC_SUPABASE_ANON_KEY
ENV NEXT_PUBLIC_APP_URL=$NEXT_PUBLIC_APP_URL
ENV NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=$NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY

# Server-side vars: dummy values at build time so module-level inits don't throw.
# Real values are injected by Railway at runtime (process.env is re-read on server start).
ARG SUPABASE_SERVICE_ROLE_KEY=build_placeholder
ARG GOOGLE_GEMINI_API_KEY=build_placeholder
ARG OPENAI_API_KEY=build_placeholder
ARG ANTHROPIC_API_KEY=build_placeholder
ARG RESEND_API_KEY=re_build_placeholder
ARG STRIPE_SECRET_KEY=sk_build_placeholder
ARG TWILIO_ACCOUNT_SID=build_placeholder
ARG TWILIO_AUTH_TOKEN=build_placeholder
ARG WHATSAPP_GATEWAY_TOKEN=build_placeholder
ARG WHATSAPP_GATEWAY_URL=build_placeholder
ARG WHATSAPP_TEST_BU_ID=build_placeholder
ARG DEEPGRAM_API_KEY=build_placeholder
ARG ELEVENLABS_API_KEY=build_placeholder
ENV SUPABASE_SERVICE_ROLE_KEY=$SUPABASE_SERVICE_ROLE_KEY
ENV GOOGLE_GEMINI_API_KEY=$GOOGLE_GEMINI_API_KEY
ENV OPENAI_API_KEY=$OPENAI_API_KEY
ENV ANTHROPIC_API_KEY=$ANTHROPIC_API_KEY
ENV RESEND_API_KEY=$RESEND_API_KEY
ENV STRIPE_SECRET_KEY=$STRIPE_SECRET_KEY
ENV TWILIO_ACCOUNT_SID=$TWILIO_ACCOUNT_SID
ENV TWILIO_AUTH_TOKEN=$TWILIO_AUTH_TOKEN
ENV WHATSAPP_GATEWAY_TOKEN=$WHATSAPP_GATEWAY_TOKEN
ENV WHATSAPP_GATEWAY_URL=$WHATSAPP_GATEWAY_URL
ENV WHATSAPP_TEST_BU_ID=$WHATSAPP_TEST_BU_ID
ENV DEEPGRAM_API_KEY=$DEEPGRAM_API_KEY
ENV ELEVENLABS_API_KEY=$ELEVENLABS_API_KEY

# Build Next.js app
ENV NEXT_TELEMETRY_DISABLED=1
RUN npm run build

# Runtime
EXPOSE 3000
ENV PORT=3000
ENV NODE_ENV=production

CMD ["npm", "run", "start"]
