import { NextRequest, NextResponse } from 'next/server'
import { supabaseAdmin } from '@/lib/supabase'

// GET - Fetch all business units (admin only)
export async function GET(request: NextRequest) {
  try {
    const { data, error } = await supabaseAdmin
      .from('business_units')
      .select('*')
      .order('created_at', { ascending: false })

    if (error) throw error

    return NextResponse.json({
      success: true,
      business_units: data
    })
  } catch (error) {
    console.error('Error fetching business units:', error)
    return NextResponse.json(
      { error: 'Failed to fetch business units' },
      { status: 500 }
    )
  }
}

// POST - Create new business unit
export async function POST(request: NextRequest) {
  try {
    const body = await request.json()
    const { name, slug, email, phone, subscription_tier } = body

    if (!name || !slug) {
      return NextResponse.json(
        { error: 'Name and slug are required' },
        { status: 400 }
      )
    }

    // Check if slug already exists
    const { data: existing } = await supabaseAdmin
      .from('business_units')
      .select('id')
      .eq('slug', slug)
      .single()

    if (existing) {
      return NextResponse.json(
        { error: 'Slug already exists' },
        { status: 400 }
      )
    }

    // Create business unit (API key will be auto-generated by trigger)
    const { data, error } = await supabaseAdmin
      .from('business_units')
      .insert([{
        name,
        slug,
        email,
        phone,
        subscription_tier: subscription_tier || 'free'
      }])
      .select()
      .single()

    if (error) throw error

    // Create default settings
    await supabaseAdmin
      .from('business_unit_settings')
      .insert([{
        business_unit_id: data.id
      }])

    return NextResponse.json({
      success: true,
      business_unit: data
    })
  } catch (error) {
    console.error('Error creating business unit:', error)
    return NextResponse.json(
      { error: 'Failed to create business unit' },
      { status: 500 }
    )
  }
}

// PUT - Update business unit
export async function PUT(request: NextRequest) {
  try {
    const body = await request.json()
    const { id, name, email, phone, subscription_tier, is_active } = body

    if (!id) {
      return NextResponse.json(
        { error: 'Business unit ID is required' },
        { status: 400 }
      )
    }

    const { data, error } = await supabaseAdmin
      .from('business_units')
      .update({
        name,
        email,
        phone,
        subscription_tier,
        is_active
      })
      .eq('id', id)
      .select()
      .single()

    if (error) throw error

    return NextResponse.json({
      success: true,
      business_unit: data
    })
  } catch (error) {
    console.error('Error updating business unit:', error)
    return NextResponse.json(
      { error: 'Failed to update business unit' },
      { status: 500 }
    )
  }
}

// DELETE - Delete business unit
export async function DELETE(request: NextRequest) {
  try {
    const { searchParams } = new URL(request.url)
    const id = searchParams.get('id')

    if (!id) {
      return NextResponse.json(
        { error: 'Business unit ID is required' },
        { status: 400 }
      )
    }

    const { error } = await supabaseAdmin
      .from('business_units')
      .delete()
      .eq('id', id)

    if (error) throw error

    return NextResponse.json({
      success: true,
      message: 'Business unit deleted successfully'
    })
  } catch (error) {
    console.error('Error deleting business unit:', error)
    return NextResponse.json(
      { error: 'Failed to delete business unit' },
      { status: 500 }
    )
  }
}
